Repository GoogleCloudPlatform/gke-migration-to-containers, pull requests merged in 2019-02, with the labels that each got.

#13 Updating dumb-init version
  container/Dockerfile
Labels: cla: yes, gke-helmsman, size/XS

#14 fix broken link in README
  README.md
Labels: approved, cla: yes, gke-helmsman, lgtm, size/XS

#16 Edits in README.md file
  README.md
Labels: approved, cla: yes, gke-helmsman, lgtm, size/M
